name: industrial-ci

on: [push, pull_request]

jobs:
  industrial_ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            distro: melodic
          - os: ubuntu-20.04
            distro: noetic
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: {ROS_DISTRO: "${{ matrix.distro }}" }
